import React from "react";

const ReactComponenetcatch = () => {
    return(
        <div className="max-w-4xl p-6 mt-10">
        <h1 className="text-3xl text-blue-500 font-semibold mb-3">React Component Catch Event</h1>
        <p>The <span className="text-red-400 bg-gray-50">componentDidCatch()</span> method is called when an error occurs during rendering, in a lifecycle method, or in any child component. It is used to create Error Boundaries in a React application. Since it runs during the commit phase, side effects are allowed, unlike getDerivedStateFromError(). This method is also commonly used for error logging.</p>
       
       <h2 className="text-2xl text-gray-800 font-semibold mt-5">Syntax</h2>
     <pre className="bg-gray-200 p-4 rounded-lg mt-5 overflow-x-auto text-sm">
  <code className="font-mono text-gray-900">

    <span className="text-blue-700">componentDidCatch</span>(error, info)

  </code>
</pre>

       <p className="mt-5">Two values are passed to the method: error and info.</p>
       <ul className="list-[square] mt-5">
        <li>error: The actual error generated by a child component.</li>
        <li>info: Details about the component hierarchy that caused the error.</li>
       </ul>

       <h2 className="text-2xl text-gray-800 font-semibold mt-10 mb-3">Creating React Application:</h2>
       <p><span className="text-xl font-semibold">Step 1</span>: Create a React application using the following command:</p>
      <pre className="bg-gray-200 p-4 rounded-lg mt-5 mb-10 overflow-x-auto text-sm">
  <code className="font-mono text-gray-900">

    <span className="text-red-600">npx</span>{" "}
    <span className="text-blue-700">create-react-app</span>{" "}
    <span className="text-yellow-700">foldername</span>

  </code>
</pre>

        <p><span className="text-xl font-semibold">Step 2</span>: After creating your project folder i.e. folder name, move to it using the following command:</p>
      <pre className="bg-gray-200 p-4 rounded-lg mt-5 overflow-x-auto text-sm">
  <code className="font-mono text-gray-900">

    <span className="text-red-600">cd</span>{" "}
    <span className="text-yellow-700">foldername</span>

  </code>
</pre>

       <h1 className="text-2xl text-gray-800 font-semibold mt-10 mb-3">Example</h1>
       <p>Program to Demonstrate the Use of the <span className="text-red-400 bg-gray-50">componentDidCatch()</span> Method</p>
       <h2 className="mt-5 text-2xl text-gray-800 font-semibold">Source File: App.js</h2>
      <pre className="bg-gray-200 p-4 rounded-lg mt-5 overflow-x-auto text-sm">
  <code className="font-mono text-gray-900">

    <span className="text-purple-700">import</span>{" "}
    <span className="text-green-700">React</span>, {"{"} Component {"}"}{" "}
    <span className="text-purple-700">from</span>{" "}
    <span className="text-yellow-700">'react'</span>;
    {"\n\n"}

    <span className="text-purple-700">export</span>{" "}
    <span className="text-purple-700">default</span>{" "}
    <span className="text-purple-700">class</span>{" "}
    <span className="text-green-700">App</span>{" "}
    <span className="text-purple-700">extends</span>{" "}
    <span className="text-green-700">Component</span> {"{"}
    {"\n"}

    {"  "}
    <span className="text-gray-500">// Initializing the state</span>
    {"\n"}

    {"  "}
    state = {"{"}
    error: false
    {"}"};
    {"\n\n"}

    {"  "}
    <span className="text-blue-700">componentDidCatch</span>(error) {"{"}
    {"\n"}

    {"    "}
    this.<span className="text-blue-700">setState</span>({"{"}
    error: true
    {"}"});
    {"\n"}

    {"  "}
    {"}"}
    {"\n\n"}

    {"  "}
    <span className="text-blue-700">render</span>() {"{"}
    {"\n"}

    {"    "}
    <span className="text-purple-700">return</span> (
    {"\n"}

    {"      "}
    &lt;<span className="text-red-600">React.StrictMode</span>&gt;
    {"\n"}

    {"        "}
    &lt;<span className="text-red-600">div</span>&gt;
    {"\n"}

    {"          "}
    {"{"}this.state.error ? (
    &lt;<span className="text-red-600">div</span>&gt;Some error&lt;/<span className="text-red-600">div</span>&gt;
    ) : (
    &lt;<span className="text-green-700">GFGComponent</span> /&gt;
    ){"}"}
    {"\n"}

    {"        "}
    &lt;/<span className="text-red-600">div</span>&gt;
    {"\n"}

    {"      "}
    &lt;/<span className="text-red-600">React.StrictMode</span>&gt;
    {"\n"}

    {"    "}
    );
    {"\n"}

    {"  "}
    {"}"}
    {"\n"}

    {"}"}
    {"\n\n"}

    <span className="text-purple-700">class</span>{" "}
    <span className="text-green-700">GFGComponent</span>{" "}
    <span className="text-purple-700">extends</span>{" "}
    <span className="text-green-700">Component</span> {"{"}
    {"\n\n"}

    {"  "}
    <span className="text-gray-500">// GFGComponent throws error as state is not defined</span>
    {"\n\n"}

    {"  "}
    <span className="text-blue-700">render</span>() {"{"}
    {"\n"}
    {"    "}
    <span className="text-purple-700">return</span>{" "}
    &lt;<span className="text-red-600">h1</span>&gt;{"{"}this.state.heading{"}"}&lt;/<span className="text-red-600">h1</span>&gt;;
    {"\n"}
    {"  "}
    {"}"}
    {"\n"}

    {"}"}

  </code>
</pre>

       <p className="mt-10"><span className="text-xl font-semibold">Steps to Run the Application</span>: Run the application by executing the following command from the project’s root directory.</p>
     <pre className="bg-gray-200 p-4 rounded-lg mt-5 overflow-x-auto text-sm">
  <code className="font-mono text-gray-900">

    <span className="text-red-600">npm</span>{" "}
    <span className="text-blue-700">start</span>

  </code>
</pre>

      
       
       
        </div>
    )
} 

export default ReactComponenetcatch;