import React from "react";

const ReactComponenetcatch = () => {
    return(
        <div className="max-w-4xl p-6 mt-10">
        <h1 className="text-3xl text-blue-500 font-semibold mb-3">React Component Catch Event</h1>
        <p>The <span className="text-red-400 bg-gray-50">componentDidCatch()</span> method is called when an error occurs during rendering, in a lifecycle method, or in any child component. It is used to create Error Boundaries in a React application. Since it runs during the commit phase, side effects are allowed, unlike getDerivedStateFromError(). This method is also commonly used for error logging.</p>
       
       <h2 className="text-2xl text-gray-800 font-semibold mt-5">Syntax</h2>
       <pre className="text-green-400 bg-gray-900 p-4 rounded-lg mt-5">
        <code>
            {`componentDidCatch(error, info)`}
        </code>
       </pre>
       <p className="mt-5">Two values are passed to the method: error and info.</p>
       <ul className="list-[square] list-inside mt-5">
        <li>error: The actual error generated by a child component.</li>
        <li>info: Details about the component hierarchy that caused the error.</li>
       </ul>

       <h2 className="text-2xl text-gray-800 font-semibold mt-10 mb-3">Creating React Application:</h2>
       <p><span className="text-xl font-semibold">Step 1</span>: Create a React application using the following command:</p>
        <pre className="text-green-400 bg-gray-900 p-4 rounded-lg mt-5 mb-10">
            <code>
                {`npx create-react-app foldername`}
            </code>
        </pre>

        <p><span className="text-xl font-semibold">Step 2</span>: After creating your project folder i.e. folder name, move to it using the following command:</p>
       <pre className="text-green-400 bg-gray-900 p-4 rounded-lg mt-5">
        <code>
            {`cd foldername`}
        </code>
       </pre>

       <h1 className="text-2xl text-gray-800 font-semibold mt-10 mb-3">Example</h1>
       <p>Program to Demonstrate the Use of the <span className="text-red-400 bg-gray-50">componentDidCatch()</span> Method</p>
       <h2 className="mt-5 text-2xl text-gray-800 font-semibold">Source File: App.js</h2>
       <pre className="text-green-400 overflow-x-auto bg-gray-900 p-4 rounded-lg mt-5">
        <code>
            {`import React, { Component } from 'react';

export default class App extends Component {
  // Initializing the state
  state = {
    error: false,
  };

  componentDidCatch(error) {
    // Changing the state to true 
    // if some error occurs
    this.setState({
      error: true
    });
  }

  render() {
    return (
      <React.StrictMode>
        <div>
          {this.state.error ? <div>Some error</div> : <GFGComponent />}
        </div>
      </React.StrictMode>
    );
  }
}

class GFGComponent extends Component {

  // GFGComponent throws error as state of 
  // GFGCompnonent is not defined
  
  render() {
    return <h1>{this.state.heading}</h1>;
  }
}`}
        </code>
       </pre>

       <p className="mt-10"><span className="text-xl font-semibold">Steps to Run the Application</span>: Run the application by executing the following command from the project’s root directory.</p>
       <pre className="text-green-400 bg-gray-900 p-4 rounded-lg mt-5">
        <code>
            {`npm start`}
        </code>
       </pre>

       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
       
        </div>
    )
} 

export default ReactComponenetcatch;